use pathsearch::find_executable_in_path;

pub fn check(com: &str, par: &str) -> bool {
    let mut success = true;
    match com {
        "admin" => (),
        "alias" => (),
        "ar" => (),
        "asa" => (),
        "at" => (),
        "awk" => (),
        "basename" => (),
        "batch" => (),
        "bc" => (),
        "bg" => (),
        "cal" => (),
        "cat" => (),
        "cc" => (),
        "cd" => (),
        "cflow" => (),
        "chgrp" => (),
        "chmod" => (),
        "chown" => (),
        "cksum" => (),
        "cmp" => (),
        "comm" => (),
        "command" => (),
        "compress" => (),
        "cp" => (),
        "cron" => (),
        "csplit" => (),
        "ctags" => (),
        "cut" => (),
        "cxref" => (),
        "date" => (),
        "dd" => (),
        "delta" => (),
        "df" => (),
        "diff" => (),
        "dirname" => (),
        "du" => (),
        "echo" => println!("{}", par),
        "ed" => (),
        "env" => (),
        "ex" => (),
        "expand" => (),
        "expr" => (),
        "false" => (),
        "fc" => (),
        "fg" => (),
        "file" => (),
        "find" => (),
        "fold" => (),
        "fuser" => (),
        "gencat" => (),
        "get" => (),
        "getconf" => (),
        "getopts" => (),
        "gettext" => (),
        "grep" => (),
        "hash" => (),
        "head" => (),
        "iconv" => (),
        "id" => (),
        "ipcrm" => (),
        "ipcs" => (),
        "jobs" => (),
        "join" => (),
        "kill" => (),
        "lex" => (),
        "link" => (),
        "ln" => (),
        "locale" => (),
        "localedef" => (),
        "logger" => (),
        "logname" => (),
        "lp" => (),
        "ls" => (),
        "m4" => (),
        "mailx" => (),
        "make" => (),
        "man" => (),
        "mesg" => (),
        "mkdir" => (),
        "mkfifo" => (),
        "more" => (),
        "msgfmt" => (),
        "mv" => (),
        "newgrp" => (),
        "ngettext" => (),
        "nice" => (),
        "nl" => (),
        "nm" => (),
        "nohup" => (),
        "od" => (),
        "paste" => (),
        "patch" => (),
        "pathchk" => (),
        "pax" => (),
        "pr" => (),
        "printf" => (),
        "prs" => (),
        "ps" => (),
        "pwd" => (),
        "read" => (),
        "readlink" => (),
        "realpath" => (),
        "renice" => (),
        "rm" => (),
        "rmdel" => (),
        "rmdir" => (),
        "sact" => (),
        "sccs" => (),
        "sed" => (),
        "sh" => (),
        "sleep" => (),
        "sort" => (),
        "split" => (),
        "strings" => (),
        "strip" => (),
        "stty" => (),
        "tabs" => (),
        "tail" => (),
        "talk" => (),
        "tee" => (),
        "test" => (),
        "time" => (),
        "timeout" => (),
        "touch" => (),
        "tput" => (),
        "tr" => (),
        "true" => (),
        "tsort" => (),
        "tty" => (),
        "type" => {
            if BUILTINS.contains(&par) {
                println!("{} is a shell builtin", par)
            } else if let Some(path) = find_executable_in_path(&par) {
                println!("{} is {}", par, path.display());
            } else {
                println!("{}: not found", par)
            }
        }
        "ulimit" => (),
        "umask" => (),
        "unalias" => (),
        "uname" => (),
        "uncompress" => (),
        "unexpand" => (),
        "unget" => (),
        "uniq" => (),
        "unlink" => (),
        "uucp" => (),
        "uudecode" => (),
        "uuencode" => (),
        "uustat" => (),
        "uux" => (),
        "val" => (),
        "vi" => (),
        "wait" => (),
        "wc" => (),
        "what" => (),
        "who" => (),
        "write" => (),
        "xargs" => (),
        "xgettext" => (),
        "yacc" => (),
        "zcat" => (),
        _ => success = false,
    }
    success
}

// should possibly be 156 with exit
// static BUILTINS: [&str; 155] = [
static BUILTINS: [&str; 3] = [
    // "admin",
    // "alias",
    // "ar",
    // "asa",
    // "at",
    // "awk",
    // "basename",
    // "batch",
    // "bc",
    // "bg",
    // "cal",
    // "cat", // ALERT THIS IS NOT RIGHT ALERT
    // "cc",
    // "cd",
    // "cflow",
    // "chgrp",
    // "chmod",
    // "chown",
    // "cksum",
    // "cmp",
    // "comm",
    // "command",
    // "compress",
    // // "cp",
    // "cron",
    // "csplit",
    // "ctags",
    // "cut",
    // "cxref",
    // "date",
    // "dd",
    // "delta",
    // "df",
    // "diff",
    // "dirname",
    // "du",
    "echo", // "ed",
    // "env",
    // "ex",
    "exit",
    // "expand",
    // "expr",
    // "false",
    // "fc",
    // "fg",
    // "file",
    // "find",
    // "fold",
    // "fuser",
    // "gencat",
    // "get",
    // "getconf",
    // "getopts",
    // "gettext",
    // "grep",
    // "hash",
    // "head",
    // "iconv",
    // "id",
    // "ipcrm",
    // "ipcs",
    // "jobs",
    // "join",
    // "kill",
    // "lex",
    // "link",
    // "ln",
    // "locale",
    // "localedef",
    // "logger",
    // "logname",
    // "lp",
    // "ls",
    // "m4",
    // "mailx",
    // "make",
    // "man",
    // "mesg",
    // "mkdir",
    // "mkfifo",
    // "more",
    // "msgfmt",
    // "mv",
    // "newgrp",
    // "ngettext",
    // "nice",
    // "nl",
    // "nm",
    // "nohup",
    // "od",
    // "paste",
    // "patch",
    // "pathchk",
    // "pax",
    // "pr",
    // "printf",
    // "prs",
    // "ps",
    // "pwd",
    // "read",
    // "readlink",
    // "realpath",
    // "renice",
    // "rm",
    // "rmdel",
    // "rmdir",
    // "sact",
    // "sccs",
    // "sed",
    // "sh",
    // "sleep",
    // "sort",
    // "split",
    // "strings",
    // "strip",
    // "stty",
    // "tabs",
    // "tail",
    // "talk",
    // "tee",
    // "test",
    // "time",
    // "timeout",
    // "touch",
    // "tput",
    // "tr",
    // "true",
    // "tsort",
    // "tty",
    "type",
    // "ulimit",
    // "umask",
    // "unalias",
    // "uname",
    // "uncompress",
    // "unexpand",
    // "unget",
    // "uniq",
    // "unlink",
    // "uucp",
    // "uudecode",
    // "uuencode",
    // "uustat",
    // "uux",
    // "val",
    // "vi",
    // "wait",
    // "wc",
    // "what",
    // "who",
    // "write",
    // "xargs",
    // "xgettext",
    // "yacc",
    // "zcat",
];
